### ISSUE TITLE
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded. Error, occurs when trying to scrape

### ISSUE THREAD

**Issue by Madhav1-web** [amineboutarfi/google_maps_scraper#3]
When trying to scrape the website, I am facing the following error

```
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("xpath=(//div[@role=\"article\"])[1]")
============================================================
```

On line number 70:
`page.hover('(//div[@role="article"])[1]')`

**Comment by jayportlmedia** [comment]
Also receiving this error. Looks like google has removed the role="article" property on the divs.

**Comment by Madhav1-web** [comment]
did you found any solutions to the same?

**Comment by ekenmapeter** [comment]
i was able to fix the css XPath issue

**Comment by amineboutarfi** [comment]
I fixed the xpath issues. Will push changes in a bit!
