### ISSUE TITLE
Address Data Extraction Issue and Resolution in Google Maps Scraping Script

### ISSUE THREAD

**Issue by NomanJu** [amineboutarfi/google_maps_scraper#6]
I hope this message finds you well. I wanted to take a moment to express my heartfelt appreciation for your instrumental role in enhancing the Google Maps scraping script. Your expertise and dedication have truly made a significant difference, and I am extremely grateful for your contributions.

Issues Faced:

Inconsistent data extraction for the name field. Sometimes the name column in the output file was populated, and other times it remained empty.
Changes Made:

Moved the name_xpath to the end of the field extraction list to mitigate the inconsistent data extraction issue.
Added a new temp field called abcd to collect the business name from a different location on the popup window, using the abcd_xpath.

These changes and modifications were made to ensure more reliable and consistent extraction of the business name data, addressing the issue of empty name columns in the output file.

**UPDATE** name_xpath is still not working.

[G-Map.txt](https://github.com/amineboutarfi/google_maps_scraper/files/12331353/G-Map.txt)

**Comment by Prodigetk** [comment]
When it says "arrived at all available" it is not extracting the business name, but when it reaches the amount noted by total then it scrapes the name aswell

**Comment by Surgical17** [comment]
Can confirm the name_xpath is still not working. Anyone found a workaround or solution?

**Comment by amineboutarfi** [comment]
@NomanJu @Surgical17 I believe the issue are fixed now! Please reopen if not
