### ISSUE TITLE
Xpath Issue

### ISSUE THREAD

**Issue by mecrayavcin** [amineboutarfi/google_maps_scraper#7]
Hi 
First of all thanks for sharing code with us.
There is a problem with Xpath.
Before i worked with some different type of bots and I know what is Xpath.

In this code review and title xpathes are broken.
I know correct paths but they also do not work. How it can be possible?

1) //h1[@class] 
I tried this not worked. This pulls H1 tag and if i use //h1[@class]/text() also it gets Title.
But i only used //h1[@class] because in your code

if listing.locator(name_xpath).count() > 0:
                business.name = listing.locator(name_xpath).inner_text()
There is a .inner_text() function so it pulls texts. So i did not use //h1[@class]/text() i used only //h1[@class] 
When i check from Chrome Inspect, it only point the title of bussiness which is in the pop ups!

But this not worked when i tried this path on the code. Title column is still emty!

2) I installed Selectorhub Chrome Plugin and get Abs x path for name!
/html[1]/body[1]/div[3]/div[8]/div[9]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/h1[1]
But it did not worked.

What is the problem in here? Both xpathes true but not worked why?
Thanks

**Comment by matheusabel96** [comment]
Have you managed to workaround this issue?

**Comment by mecrayavcin** [comment]
> Have you managed to workaround this issue?

NO :( not yet

**Comment by amineboutarfi** [comment]
I believe it's fixed now @mecrayavcin, Reopen issue if not! Thanks
