### ISSUE TITLE
Error: strict mode violation: locator

### ISSUE THREAD

**Issue by On3n3xus** [amineboutarfi/google_maps_scraper#8]
playwright._impl._errors.Error: Error: strict mode violation: locator("//a[contains(@href, \"https://www.google.com/maps/place\")]").first.locator("..").locator("//span[@role=\"img\"]") resolved to 2 elements:
    1) <span role="img" class="ZkP5Je" aria-label="4.4 stars …>…</span> aka get_by_label("stars 5,141 Reviews")
    2) <span role="img" aria-label="Price: Inexpensive">$</span> aka locator("span:nth-child(3) > span:nth-child(2)").first

**Comment by amineboutarfi** [comment]
bug is fixed. Thanks for the report @On3n3xus . Closing this issue!
